# Generated by Django 3.2.5 on 2022-02-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greetings', models.CharField(default='', max_length=20)),
                ('about_quote', models.CharField(max_length=999)),
                ('image', models.ImageField(upload_to='images/about/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('category', models.CharField(default='', max_length=50)),
                ('details', models.CharField(max_length=255)),
                ('github_url', models.CharField(default='', max_length=300)),
                ('image', models.ImageField(upload_to='images/skill')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/skill/')),
            ],
        ),
    ]
